Feat/side bar
leoFagundes/cine-drivein-admin pull request #4
Opened 2024-02-07 01:01 UTC by Sabanai104

2024-02-07 10:10 UTC, leoFagundes requested changes
Dei sugestão de 2 mudanças só, ai vê o que você acha e pode dar merge

2024-02-07 10:10 UTC, leoFagundes commented on src/Components/Organism/Sidebar/index.tsx
> +      >
Mano,  a animação está meio rápida, seria bom colocar uma 'duration'. Vai mudar pouca coisa mas vê o que tu acha:

```
      <motion.div
        className={styles.container}
        animate={isOpen ? "open" : "closed"}
        variants={variants}
        transition={{ duration: 0.5, ease: "easeInOut" }}
      >
```

2024-02-07 10:10 UTC, leoFagundes commented on src/Components/Organism/Sidebar/index.tsx
> +            const marginTop = index === 0 ? '32px' : '24px';
O que vc acha de uma marginTop um pouco menor entre os itens? 16px ou 20px em vez de 24px

2024-02-08 01:40 UTC, Sabanai104 commented
> Dei sugestão de 2 mudanças só, ai vê o que você acha e pode dar merge

Otimos pontos maan!!!

2024-02-08 09:42 UTC, leoFagundes approved these changes

2024-02-08 09:52 UTC, merged