feat: update admin template
leoFagundes/cine-drivein-admin pull request #5
Opened 2024-02-08 20:36 UTC by leoFagundes

2024-02-09 20:11 UTC, leoFagundes commented
Uma pergunta man, acha que vale a pena adicionar o Loading no código abaixo? Ou adicionar ele apenas quando fizermos algum request no back?

```
  const renderContent = () => {
    if (currentPage === "home") {
      return <Home />;
    }
    if (currentPage === "profile") {
      // return <Profile />;
      return 'profile'
    }
    if (currentPage === "order") {
      // return <Orders />;
      return 'order'
    }
    if (currentPage === "stock") {
      // return <Stock />;
      return 'stock'
    }
    if (currentPage === "register") {
      // return <Register />;
      return 'register'
    }
    if (currentPage === "users") {
      // return <Users />;
      return 'users'
    }

    return <Home />;
  };
```

2024-02-12 15:10 UTC, Sabanai104 requested changes

2024-02-12 15:10 UTC, Sabanai104 commented on src/routes.tsx
> +      <Route path="/" element={<LayoutWithSidebar />} />
Maan, vamo fazer asim, aqui a ideia é a gente criar no template um AppTemplate por exemplo
Ai lá dentro a gente puxa esse layoutwithsidebar e aplica a regra do que vai renderizar dentro dele nesse arquivo de page tlg?

Depois a gente cria na pages uma página tipo AppPage ou algo assim e chama o nosso template. Ai renderiza isso na routes, que tal?

2024-02-12 15:10 UTC, Sabanai104 commented on src/Pages/Login/index.tsx
> +      />
Maan, aqui se ta chamando duas vezes o mesmo componente, o ideal seria vc chamar o alert uma vez e só trocar as props que vc passa pra ele

2024-02-12 15:10 UTC, Sabanai104 commented on src/Pages/Login/index.tsx
> +  const [showUnauthorizedPageAccessAlert, setShowUnauthorizedPageAccessAlert] = useState(false);
Se vc chamar o alert só uma vez vc n tem mais a necessidade desse state aquii. LER COMENTARIO DE BAIXO SOBRE O ALERT.
```suggestion

```

2024-02-12 15:10 UTC, Sabanai104 commented on src/Components/Organism/LayoutWithSidebar/index.tsx
> +  }, [from, navigate, isLoggedIn]);
Seguindo minha sugestão do templete e pages (LER LA EMBAIXO). Vc pode jogar toda essa lógica para o template
```suggestion
```

2024-02-12 17:34 UTC, merged